### ISSUE TITLE
Not flagging escaping violations

### ISSUE THREAD

**Issue by pdewouters** [humanmade/linter-bot#109]
I am not 100% sure this is a bug in the linter bot, it might be related to the coding standards library because it seems my php codesniffer IDE integration isn't flagging missing escaping either, maybe since 0.7. IT could also be related to our custom phpcs config.

This is an example of code that was missed by the linter bot

`<div class="statistics__tabs filters filters-wrapper" id="<?php echo $tabs_id ?>" data-tab="<?php echo $tabs_id ?>">`

I will do some testing myself - if I can reproduce locally then it means the bot isn't at fault

**Comment by pdewouters** [comment]
I can reproduce locally by running phpcs from the command line, so it has to do with the coding standards package, not the bot

**Comment by pdewouters** [comment]
Is this because we are excluding the rule `<exclude name="WordPress.Security.EscapeOutput" />`, so if we want to flag missing escaping, we need to include the VIP rules?

**Comment by pdewouters** [comment]
yes, adding `<rule ref="WordPress-VIP" />` as per documentation fixes this

**Comment by mikeselander** [comment]
Associated Coding Standards issue: https://github.com/humanmade/coding-standards/issues/102
