### ISSUE TITLE
PHPCompatibility error

### ISSUE THREAD

**Issue by pdewouters** [humanmade/linter-bot#110]
<img width="602" alt="Screenshot 2019-10-04 at 10 59 29" src="https://user-images.githubusercontent.com/30460/66199261-1dbe3b80-e696-11e9-902e-c071990c99d4.png">

locally this runs fine `vendor/bin/phpcs --standard=phpcs.ruleset.xml .`

**Comment by rmccue** [comment]
Found the issue; dealerdirect/phpcodesniffer-composer-installer doesn't work because we're not installing via Composer. We need to add this to the list of installed paths.
