### ISSUE TITLE
The linter-bot not reporting ESLint warnings

### ISSUE THREAD

**Issue by ntwb** [humanmade/linter-bot#131]
Over on a project I am working on I'm seeing unexpected results from the linter-bot

The linter-bot has only recently been added to this project

The linter-bot was reporting the following:
> hm-linter displays: 1 PHPCS error and 5 ESLint warnings

Once I resolved the single outstanding PHPCS error I would expect for the linterr-bot to continue to display the 5 ESLint warnings, instead it displays:
> hm-linter displays: All checks passed

As the repo this issue relates to a private repo I've posted links to the related code and pull requests in HM Slack [here](https://hmn.slack.com/archives/C03K3J34A/p1587602378171900)

**Comment by mikeselander** [comment]
This was fixed in #133, just need to deploy it.
