### ISSUE TITLE
How do projects configure env settings?

### ISSUE THREAD

**Issue by tareiking** [humanmade/linter-bot#155]
I wanna toggle `CHECK_ANNOTATION_ONLY_RELATED` for SC (HM bot isn't configured to run there because noise), but I'm not sure where I can set these env variables project side?

Is it possible to add to `hmlinter.yml` or somewhere in GH project settings? Would be excellent to have an example within the readme as some settings are probably useful.

`CHECK_ANNOTATION_ONLY_RELATED` and `FORCE_NEUTRAL_STATUS` are two examples, might be obvious - but I don't want to add project noise testing it out.

**Comment by rmccue** [comment]
These aren't designed to be configurable per project; they're configuration only at the bot level, as we run two (altis-review and hmlinter). The configuration only exists so we can share the codebase across the bots, but the bots are designed to have consistent functionality within themselves where possible.
