### ISSUE TITLE
Add dependency for `jsx-a11y/anchor-is-valid`

### ISSUE THREAD

**Issue by peterwilsoncc** [humanmade/linter-bot#67]
An dependency error is being throw for the anchor is valid rule in version `^0.5.0`.

Linterbot output:

```
{
  "line": 1,
  "column": 1,
  "severity": "error",
  "message": "Definition for rule 'jsx-a11y/anchor-is-valid' was not found",
  "source": "jsx-a11y/anchor-is-valid"
}
```

The error appears to be thrown on line one of all JavaScript files.

**Comment by rmccue** [comment]
I think this is fixed by the updates to ESLint in coding-standards for (unreleased) 0.6, @kadamwhite @mikeselander?
