### ISSUE TITLE
Update WPCS Coding Standards and dependencies to latest

### ISSUE THREAD

**Issue by fklein-lu** [humanmade/linter-bot#69]
Update the WordPress Coding Standards and the related PHPCS dependencies to the latest version, to get the same configuration as those pulling in the HM Coding Standards on local.

**Comment by mikeselander** [comment]
Is there anything in particular holding this back? It's still spilling false positives on several clients and it'd be great to have this fixed.

**Comment by mikeselander** [comment]
@rmccue as I understand it, this is handled in https://github.com/humanmade/coding-standards and there's not really anything to update here. Is that correct or do we need to bump a version here after we release 0.6.0?

**Comment by rmccue** [comment]
We are already up-to-date on 0.5.0 though, so closing this.
