### ISSUE TITLE
Run only on changes in PR? Linting failed (33886 errors, 20567 warnings).

### ISSUE THREAD

**Issue by elearningplugins** [humanmade/linter-bot#77]
I keep seeing this error:

Linting failed (33886 errors, 20567 warnings).

(54173 notices occurred in your codebase, but were on files/lines not included in this PR.)

=============

Anyway to change it so that it only runs on the changes in the pr instead of against everything?

**Comment by rmccue** [comment]
We intentionally don't have this behaviour to encourage fixing errors. If these aren't errors you want to fix, [ignore the files instead](https://github.com/humanmade/coding-standards#excluding-files).
