### ISSUE TITLE
Add Stylelint to Linter Bot

### ISSUE THREAD

**Issue by mikeselander** [humanmade/linter-bot#80]
We will shortly have Stylelint standards published to NPM as a package and it would be incredible useful from a reviewer's perspective to be able to run Stylelint in Linter Bot to evaluate both CSS and SCSS.

This will involve adding Stylelint evaluation of `.stylelintrc` and `.stylelinignore` files, pulling Stylelint core in, and (once published) our Styleling standards being applied by default.

My only concern with adding a whole new linter into Linter Bot is that it could immediately spam repos that Linter Bot is on with hundreds of CSS issues if we turn it on by default to start with.

To alleviate the above issue, I propose that we add Stylelint in a turned-off state by default. Projects can chose when to turn on Stylelint to use on their codebase and have a period of opportunity to fix their codebase before Linter Bot starts spitting out errors.

Then, after ~ 6 months with ratcheting notice given internally, we turn on Stylelint by default and each project can have the opportunity to turn Linter Bot off.

Any thoughts/issues @rmccue?

**Comment by jay-oswald** [comment]
Hey @mikeselander is there any chance that this will be happening?

**Comment by mikeselander** [comment]
@jay-oswald yes, this will definitely be happening but it's a bit of an as-I-get-time task, so I wouldn't expect it for at least another month or two.

**Comment by rmccue** [comment]
psst, if you'd like to get this earlier, feel free to send a PR! 😃

**Comment by jay-oswald** [comment]
@mikeselander good to hear! also @rmccue I would love to, but don't have time at work, and getting married at the end of the year, planning a wedding takes so much longer than it should haha

**Comment by rmccue** [comment]
@jay-oswald Congratulations! ✨
