### ISSUE TITLE
Re-run upon failure automatically

### ISSUE THREAD

**Issue by mikeselander** [humanmade/linter-bot#81]
Linter Bot can fail without cause or explanation, but run perfectly fine on subsequent attempts. It would be a neat feature or flag if Linter Bot could retry once or twice upon a failure to read the code, thus avoiding the need to traverse multiple pages and click `Re-run`.

**Comment by rmccue** [comment]
Actually, we should just fix the failures. The main one is #66, which is fixed but not yet deployed.

**Comment by mikeselander** [comment]
Certainly we should, but it would also be nice to have a redundancy in place if a project desires it.

**Comment by rmccue** [comment]
IMO, it's better to leave this for the re-run button in GitHub so that we can keep catching the errors. Keeping those failures visible is much better IMO.

**Comment by mikeselander** [comment]
I agree, let's close this 👍
