### ISSUE TITLE
Bot Queues Perpetually

### ISSUE THREAD

**Issue by mikeselander** [humanmade/linter-bot#90]
I've found that recently the bot has been queueing persistently and more often than not, telling it to `Re-run all` won't actually allow it to finish. This seems to happen on specific Pull Requests in repos, but not all PRs. I can provide examples via DM if necessary.

**Comment by kadamwhite** [comment]
I’m currently working on a project where we have this issue on all PRs; I haven’t seen linter bot actually run all week. Can provide link via DM

**Comment by rmccue** [comment]
I'm unable to track this down, I can't find the requests in Lambda. Will look further once I can find another request that fails.

**Comment by rmccue** [comment]
This appears to be fixed finally. The issue was that a large project was using up the entire `/tmp` space, and we never cleared out that directory. This caused subsequent runs to fail with ENOSPC errors.

Fixed in #91.
