### ISSUE TITLE
Linter continously fails without a visible reason

### ISSUE THREAD

**Issue by shadyvb** [humanmade/linter-bot#93]
We're having issues on a client project where the linter fails with the following log:

>>>
Failed to run hmlinter
Could not run: ............................................................ 60 / 94 (64%)
.................................. 94 / 94 (100%)

{"totals":{"errors":0,"warnings":0,"fixable":0},"files":{"healthcheck.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]},"content/redacted/file/name.php":{"errors":0,"warnings":0,"messages":[]}}}Time: 2.18 secs; Memory: 14Mb

Note that I've redacted file names for privacy reasons.

**Comment by rmccue** [comment]
@shadyvb Looks like your phpcs ruleset might include `--progress` or similar? This isn't compatible with hm-linter, as it requires JSON output with no status or progress information.

**Comment by shadyvb** [comment]
@rmccue Thanks! that fixed it 👍
